"""empty message

Revision ID: 96138eacb25d
Revises: 4c29c6eea6a4
Create Date: 2024-05-29 19:56:34.914150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96138eacb25d'
down_revision = '4c29c6eea6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###
